// <auto-generated />
using System;
using FluencyHub.PaymentProcessing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluencyHub.BoundedContexts.PaymentProcessing.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20250525195712_IgnoreEnrollmentProperty")]
    partial class IgnoreEnrollmentProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("FluencyHub.PaymentProcessing.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FluencyHub.PaymentProcessing.Domain.Payment", b =>
                {
                    b.OwnsOne("FluencyHub.PaymentProcessing.Domain.CardDetails", "CardDetails", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CardHolderName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExpiryMonth")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExpiryYear")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MaskedCardNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PaymentId");

                            b1.ToTable("CardDetails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("CardDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
